# Prefer the newest standard Qt installation under C:/Qt, regardless of its
# minor version; fall back to user-provided environment variables.

file(GLOB _cs106b_qt_candidates LIST_DIRECTORIES true "C:/Qt/*/mingw_64")
list(SORT _cs106b_qt_candidates COMPARE STRING ORDER DESCENDING)
set(_cs106b_qt "")
foreach(_candidate IN LISTS _cs106b_qt_candidates)
    if(EXISTS "${_candidate}/lib/cmake/Qt6/Qt6Config.cmake")
        set(_cs106b_qt "${_candidate}")
        break()
    endif()
endforeach()
if(NOT _cs106b_qt AND DEFINED ENV{CS106B_QT_ROOT} AND EXISTS "$ENV{CS106B_QT_ROOT}/lib/cmake/Qt6/Qt6Config.cmake")
    set(_cs106b_qt "$ENV{CS106B_QT_ROOT}")
endif()
if(NOT _cs106b_qt)
    message(FATAL_ERROR "Qt 6 was not found under C:/Qt/*/mingw_64. Set CS106B_QT_ROOT to the Qt mingw_64 directory.")
endif()

file(GLOB _cs106b_mingw_candidates LIST_DIRECTORIES true "C:/Qt/Tools/mingw*")
list(SORT _cs106b_mingw_candidates COMPARE STRING ORDER DESCENDING)
set(_cs106b_mingw "")
foreach(_candidate IN LISTS _cs106b_mingw_candidates)
    if(EXISTS "${_candidate}/bin/g++.exe")
        set(_cs106b_mingw "${_candidate}")
        break()
    endif()
endforeach()
if(NOT _cs106b_mingw AND DEFINED ENV{CS106B_MINGW_ROOT} AND EXISTS "$ENV{CS106B_MINGW_ROOT}/bin/g++.exe")
    set(_cs106b_mingw "$ENV{CS106B_MINGW_ROOT}")
endif()
if(NOT _cs106b_mingw)
    message(FATAL_ERROR "MinGW was not found under C:/Qt/Tools/mingw*. Set CS106B_MINGW_ROOT to its root directory.")
endif()

if(EXISTS "${_cs106b_mingw}/bin/g++.exe")
    set(CMAKE_CXX_COMPILER "${_cs106b_mingw}/bin/g++.exe" CACHE FILEPATH "CS106B MinGW C++ compiler" FORCE)
endif()
set(CMAKE_PREFIX_PATH "${_cs106b_qt}" CACHE PATH "CS106B Qt installation" FORCE)

set(_cs106b_ninja "C:/Qt/Tools/Ninja")
if(NOT EXISTS "${_cs106b_ninja}/ninja.exe" AND DEFINED ENV{CS106B_NINJA})
    set(_cs106b_ninja "$ENV{CS106B_NINJA}")
endif()
if(EXISTS "${_cs106b_ninja}/ninja.exe")
    set(ENV{PATH} "${_cs106b_ninja};$ENV{PATH}")
endif()
set(ENV{PATH} "${_cs106b_qt}/bin;${_cs106b_mingw}/bin;$ENV{PATH}")
